local nameList = {
		"amgeo",
	"amphaa",
	"amphartillery",
	"amphassault",
	"amphbomb",
	"amphcon",
	"amphfloater",
	"amphraider",
	"amphraider2",
	"amphraider3",
	"amphriot",
	"amphtele",
	"arm_spider",
	"arm_venom",
	"armaak",
	"armamd",
	"armanni",
	"armarad",
	"armartic",
	"armasp",
	"armbanth",
	"armbrawl",
	"armbrtha",
	"armca",
	"armcarry",
	"armcir",
	"armcomdgun",
	"armcrabe",
	"armcsa",
	"armcybr",
	"armdeva",
	"armestor",
	"armflea",
	"armfus",
	"armham",
	"armjamt",
	"armjeth",
	"armkam",
	"armmanni",
	"armmerl",
	"armmstor",
	"armnanotc",
	"armorco",
	"armpb",
	"armpw",
	"armraven",
	"armraz",
	"armrectr",
	"armrock",
	"armsnipe",
	"armsolar",
	"armsonar",
	"armsptk",
	"armspy",
	"armstiletto_laser",
	"armtick",
	"armwar",
	"armwin",
	"armzeus",
	"assaultcruiser",
	"asteroid",
	"blackdawn",
	"bladew",
	"blastwing",
	"bomberassault",
	"bomberdive",
	"bomberlaser",
	"bomberstrike",
	"cafus",
	"capturecar",
	"cobtransport",
	"coracv",
	"corak",
	"corawac",
	"corbhmth",
	"corbtrans",
	"corcan",
	"corch",
	"corclog",
	"corcrash",
	"corcrw",
	"cordoom",
	"core_spectre",
	"corfast",
	"corfav",
	"corflak",
	"corgarp",
	"corgator",
	"corgol",
	"corgrav",
	"corhlt",
	"corhurc2",
	"corjamt",
	"corlevlr",
	"corllt",
	"cormak",
	"cormart",
	"cormex",
	"cormist",
	"cornecro",
	"corned",
	"corpyro",
	"corpyro2",
	"corrad",
	"corraid",
	"corrazor",
	"correap",
	"corrl",
	"corroach",
	"corsent",
	"corsh",
	"corshad",
	"corsilo",
	"corsktl",
	"corstorm",
	"corsumo",
	"corthud",
	"corvalk",
	"corvamp",
	"damagesink",
	"dante",
	"destroyer",
	"dynfancy_recon_base",
	"dynfancy_strike_base",
	"dynfancy_support_base",
	"dynhub_assault_base",
	"dynhub_recon_base",
	"dynhub_strike_base",
	"dynhub_support_base",
	"empiricaldpser",
	"empmissile",
	"factoryamph",
	"factorycloak",
	"factorygunship",
	"factoryhover",
	"factoryjump",
	"factoryplane",
	"factoryshield",
	"factoryship",
	"factoryspider",
	"factorytank",
	"factoryveh",
	"fakeunit",
	"fakeunit_aatarget",
	"fakeunit_los",
	"fighter",
	"fighterdrone",
	"firewalker",
	"funnelweb",
	"geo",
	"gunshipaa",
	"gunshipcon",
	"gunshipsupport",
	"heavyturret",
	"hoveraa",
	"hoverassault",
	"hoverdepthcharge",
	"hoverminer",
	"hoverriot",
	"hoverscout",
	"hovershotgun",
	"hoverskirm",
	"hoversonic",
	"jumpblackhole",
	"jumpblackhole2",
	"jumpimpulse",
	"jumpriot",
	"logkoda",
	"mahlazer",
	"missilesilo",
	"missiletower",
	"napalmmissile",
	"nebula",
	"neebcomm",
	"nest",
	"nsaclash",
	"panther",
	"puppy",
	"pw_artefact",
	"pw_dropfac",
	"pw_estorage",
	"pw_estorage2",
	"pw_garrison",
	"pw_gaspowerstation",
	"pw_generic",
	"pw_grid",
	"pw_guerilla",
	"pw_inhibitor",
	"pw_interception",
	"pw_mine",
	"pw_mine2",
	"pw_mine3",
	"pw_mstorage2",
	"pw_warpgate",
	"pw_warpgatealt",
	"pw_warpjammer",
	"pw_wormhole",
	"pw_wormhole2",
	"raveparty",
	"rocksink",
	"roost",
	"roostfac",
	"scorpion",
	"screamer",
	"seismic",
	"shieldarty",
	"shieldfelon",
	"shipaa",
	"shiparty",
	"shipassault",
	"shipcarrier",
	"shipcon",
	"shipheavyarty",
	"shipriot",
	"shipscout",
	"shipskirm",
	"shiptorpraider",
	"shiptransport",
	"slowmort",
	"spherecloaker",
	"spherepole",
	"spideraa",
	"spideranarchid",
	"spiderassault",
	"spiderriot",
	"starlight_satellite",
	"striderhub",
	"subraider",
	"subscout",
	"subtacmissile",
	"tacnuke",
	"tankriotraider",
	"tawf114",
	"tele_beacon",
	"terraunit",
	"thicket",
	"tiptest",
	"trem",
	"turrettorp",
	"vehaa",
	"wolverine_mine",
	"zenith",
}

--local humanNames = {}
--local newNamesList = {}
--for i = 1, #nameList do
--	if UnitDefNames[nameList[i]] then
--		newNamesList[#newNamesList + 1] = nameList[i]
--		humanNames[nameList[i]] = UnitDefNames[nameList[i]].humanName
--	end
--end
--Spring.Utilities.TableEcho(newNamesList, "newNamesList")
--Spring.Utilities.TableEcho(humanNames, "humanNames")

local humanNames = {
	spherecloaker = "Eraser",
	gunshipsupport = "Rapier",
	dynhub_strike_base = "Strike Support",
	amphartillery = "Kraken",
	cormart = "Pillager",
	corcrw = "Krow",
	missilesilo = "Missile Silo",
	jumpriot = "Infernal",
	armflea = "Flea",
	armfus = "Fusion Reactor",
	blastwing = "Blastwing",
	pw_mine2 = "Orbital Solar Array",
	zenith = "Zenith",
	correap = "Reaper",
	starlight_satellite = "Owl",
	screamer = "Screamer",
	vehaa = "Crasher",
	pw_generic = "Generic Neutral Structure",
	napalmmissile = "Inferno",
	turrettorp = "Urchin",
	factoryamph = "Amphibious Bot Plant",
	cordoom = "Doomsday Machine",
	trem = "Tremor",
	destroyer = "Daimyo",
	armtick = "Tick",
	cormak = "Outlaw",
	pw_mine3 = "Planetary Geothermal Tap",
	subraider = "Seawolf",
	thicket = "Thicket",
	corsh = "Dagger",
	corllt = "Lotus",
	factoryship = "Shipyard",
	tele_beacon = "Lamp",
	armrock = "Rocko",
	tawf114 = "Banisher",
	tankriotraider = "Panther",
	coracv = "Welder",
	shieldarty = "Racketeer",
	gunshipcon = "Wasp",
	roost = "Roost",
	subtacmissile = "Scylla",
	shieldfelon = "Felon",
	tiptest = "TIP test unit",
	armpw = "Glaive",
	striderhub = "Strider Hub",
	spiderriot = "Redback",
	spiderassault = "Hermit",
	gunshipaa = "Trident",
	corclog = "Dirtbag",
	dynhub_recon_base = "Recon Support",
	hoverminer = "Dampener",
	shiptorpraider = "Hunter",
	spideraa = "Tarantula",
	corrazor = "Razor",
	corgol = "Goliath",
	corch = "Quill",
	armaak = "Archangel",
	spherepole = "Scythe",
	geo = "Geothermal Generator",
	corfast = "Constable",
	dynfancy_strike_base = "Strike Trainer",
	pw_guerilla = "Guerilla Jumpgate",
	pw_estorage = "Energy Storage",
	armarad = "Advanced Radar",
	amphraider2 = "Archer",
	shipscout = "Cutter",
	pw_wormhole = "Wormhole Generator",
	shipriot = "Corsair",
	armjamt = "Sneaky Pete",
	amphbomb = "Limpet",
	arm_venom = "Venom",
	factoryjump = "Jump/Specialist Plant",
	armpb = "Gauss",
	nebula = "Nebula",
	corfav = "Dart",
	hoveraa = "Flail",
	armham = "Hammer",
	shipcon = "Mariner",
	armsptk = "Recluse",
	blackdawn = "Black Dawn",
	shipcarrier = "Reef",
	rocksink = "Rocking Damage Sink thing",
	fakeunit_aatarget = "Fake AA target",
	shipassault = "Siren",
	pw_garrison = "Field Garrison",
	shiparty = "Ronin",
	shipaa = "Zephyr",
	armamd = "Protector",
	mahlazer = "Starlight",
	dynhub_assault_base = "Guardian Support",
	armbrtha = "Big Bertha",
	armcrabe = "Crabe",
	pw_inhibitor = "Wormhole Inhibitor",
	subscout = "Lancelet",
	armrectr = "Conjurer",
	seismic = "Quake",
	armsnipe = "Spectre",
	corbhmth = "Behemoth",
	wolverine_mine = "Claw",
	scorpion = "Scorpion",
	armmstor = "Storage",
	roostfac = "Roost",
	amphriot = "Scallop",
	amphaa = "Angler",
	corsent = "Copperhead",
	armkam = "Banshee",
	raveparty = "Disco Rave Party",
	pw_wormhole2 = "Improved Wormhole",
	pw_warpjammer = "Warp Jammer",
	spideranarchid = "Anarchid",
	asteroid = "Asteroid",
	corvamp = "Hawk",
	dynfancy_recon_base = "Recon Trainer",
	pw_warpgate = "Warp Gate",
	pw_mstorage2 = "Metal Storage",
	corlevlr = "Leveler",
	corthud = "Thug",
	corjamt = "Aegis",
	missiletower = "Hacksaw",
	corpyro2 = "Pyro",
	empiricaldpser = "Empirical DPS thing",
	pw_interception = "Interception Network",
	hoverassault = "Halberd",
	cornecro = "Convict",
	shiptransport = "Surfboard",
	armwar = "Warrior",
	pw_grid = "Planetary Defense Grid",
	cafus = "Singularity Reactor",
	armstiletto_laser = "Thunderbird",
	factoryspider = "Spider Factory",
	amphtele = "Djinn",
	corstorm = "Rogue",
	jumpimpulse = "Elevator",
	pw_estorage2 = "Double Energy Storage",
	shipskirm = "Mistral",
	pw_dropfac = "Dropship Factory",
	corpyro = "Pyro",
	dante = "Dante",
	puppy = "Puppy",
	panther = "Panther",
	nest = "Nest",
	corgrav = "Newton",
	dynhub_support_base = "Engineer Support",
	armjeth = "Gremlin",
	neebcomm = "Neeb Comm",
	logkoda = "Kodachi",
	amgeo = "Advanced Geothermal",
	pw_gaspowerstation = "Gas Power Station",
	jumpblackhole2 = "Hoarder",
	bladew = "Gnat",
	terraunit = "Terraform",
	hoversonic = "Morningstar",
	armestor = "Energy Pylon",
	hoverskirm = "Trisula",
	corshad = "Raven",
	pw_mine = "Power Generator Unit",
	amphfloater = "Buoy",
	hoverscout = "Dagger",
	hoverriot = "Mace",
	fakeunit_los = "LOS Provider",
	armcybr = "Wyvern",
	hoverdepthcharge = "Claymore",
	heavyturret = "Sunlance",
	tacnuke = "Eos",
	bomberdive = "Raven",
	funnelweb = "Funnelweb",
	firewalker = "Firewalker",
	corgator = "Scorcher",
	fighterdrone = "Spicula",
	amphcon = "Conch",
	bomberassault = "Eclipse",
	armzeus = "Zeus",
	fakeunit = "Fake radar signal",
	armanni = "Annihilator",
	factoryveh = "Light Vehicle Factory",
	armsolar = "Solar Collector",
	armbrawl = "Brawler",
	arm_spider = "Weaver",
	jumpblackhole = "Placeholder",
	corned = "Mason",
	factoryshield = "Shield Bot Factory",
	factoryplane = "Airplane Plant",
	shipheavyarty = "Shogun",
	armraz = "Razorback",
	factorygunship = "Gunship Plant",
	factoryhover = "Hovercraft Platform",
	factorycloak = "Cloaky Bot Factory",
	empmissile = "Shockley",
	nsaclash = "Scalpel",
	cobtransport = "Valkyrie",
	assaultcruiser = "Vanquisher",
	corsktl = "Skuttle",
	armcarry = "Reef (Classic)",
	slowmort = "Moderator",
	fighter = "Swift",
	dynfancy_support_base = "Engineer Trainer",
	capturecar = "Dominatrix",
	factorytank = "Heavy Tank Factory",
	armbanth = "Bantha",
	corhlt = "Stinger",
	corflak = "Cobra",
	armraven = "Catapult",
	armcir = "Chainsaw",
	armartic = "Faraday",
	corroach = "Roach",
	damagesink = "Damage Sink thing",
	corvalk = "Valkyrie",
	corsilo = "Silencer",
	hovershotgun = "Punisher",
	corsumo = "Sumo",
	armspy = "Infiltrator",
	armmerl = "Impaler",
	core_spectre = "Aspis",
	corrl = "Defender",
	pw_warpgatealt = "Warp Gate",
	armnanotc = "Caretaker",
	corraid = "Ravager",
	corrad = "Radar Tower",
	armwin = "Wind/Tidal Generator",
	pw_artefact = "Ancient Artefact",
	armca = "Crane",
	corcrash = "Vandal",
	corak = "Bandit",
	amphraider3 = "Duck",
	corgarp = "Wolverine",
	armcomdgun = "Ultimatum",
	corhurc2 = "Phoenix",
	cormex = "Metal Extractor",
	armorco = "Detriment",
	bomberstrike = "Kestrel",
	armcsa = "Athena",
	armasp = "Air Repair/Rearm Pad",
	cormist = "Slasher",
	amphraider = "Grebe",
	corcan = "Jack",
	armsonar = "Sonar Station",
	bomberlaser = "Pheonix with mini-laser",
	amphassault = "Grizzly",
	armmanni = "Penetrator",
	corbtrans = "Vindicator",
	corawac = "Vulture",
	armdeva = "Stardust",
}

return {
	nameList = nameList,
	humanNames = humanNames
}